INSERT INTO Expansion VALUES
('15th Anniversary','15A'),
('Aether Revolt','AER'),
('Alara Reborn','ARB'),
('Alliances','AL'),
('Amonkhet','AKH'),
('Anthologies','ANT'),
('Antiquities','AQ'),
('Apocalypse','AP'),
('Arabian Nights','AN'),
('Archenemy','ARC'),
('Archenemy "Schemes"','ARS'),
('Archenemy: Nicol Bolas','E01'),
('Archenemy: Nicol Bolas "Schemes"','E01S'),
('Arena League','ARE'),
('Asia Pacific Land Program','APAC'),
('Avacyn Restored','AVR'),
('Battle for Zendikar','BFZ'),
('Battle Royale Box Set','BR'),
('Beatdown Box Set','BD'),
('Betrayers of Kamigawa','BOK'),
('Born of the Gods','BNG'),
('Celebration Cards','CC'),
('Champions of Kamigawa','CHK'),
('Champs','CHA'),
('Chronicles','CH'),
('Clash Pack','CLSP'),
('Classic Sixth Edition','6E'),
('Coldsnap','CS'),
('Coldsnap Theme Decks','CST'),
('Commander 2013 Edition','C13'),
('Commander 2014','C14'),
('Commander 2015','C15'),
('Commander 2016','C16'),
('Commander 2017','C17'),
('Commander Anthology','CMA'),
('Commander''s Arsenal','CRS'),
('Conflux','CFX'),
('Conspiracy: Take the Crown','CN2'),
('Conspiracy: Take the Crown "Conspiracies"','CN2C'),
('Dark Ascension','DKA'),
('Darksteel','DS'),
('Deckmasters','DM'),
('Dissension','DIS'),
('Dragon''s Maze','DGM'),
('Dragons of Tarkir','DTK'),
('Duel Decks Anthology, Divine vs. Demonic','ADVD'),
('Duel Decks Anthology, Elves vs. Goblins','AEVG'),
('Duel Decks Anthology, Garruk vs. Liliana','AGVL'),
('Duel Decks Anthology, Jace vs. Chandra','AJVC'),
('Duel Decks: Ajani vs. Nicol Bolas','AVB'),
('Duel Decks: Blessed vs. Cursed','BVC'),
('Duel Decks: Divine vs. Demonic','DVD'),
('Duel Decks: Elspeth vs. Kiora','EVK'),
('Duel Decks: Elspeth vs. Tezzeret','EVT'),
('Duel Decks: Elves vs. Goblins','EVG'),
('Duel Decks: Garruk vs. Liliana','GVL'),
('Duel Decks: Heroes vs. Monsters','HVM'),
('Duel Decks: Izzet vs. Golgari','IVG'),
('Duel Decks: Jace vs. Chandra','JVC'),
('Duel Decks: Jace vs. Vraska','JVV'),
('Duel Decks: Knights vs. Dragons','KVD'),
('Duel Decks: Mind vs. Might','MVM'),
('Duel Decks: Nissa vs. Ob Nixilis','NVO'),
('Duel Decks: Phyrexia vs. the Coalition','PVC'),
('Duel Decks: Sorin vs. Tibalt','SVT'),
('Duel Decks: Speed vs. Cunning','SVC'),
('Duel Decks: Venser vs. Koth','VVK'),
('Duel Decks: Zendikar vs. Eldrazi','ZVE'),
('Duels of the Planeswalkers','DPA'),
('Eighth Edition','8E'),
('Eighth Edition Box Set','8EB'),
('Eldritch Moon','EMN'),
('Eternal Masters','EMA'),
('European Land Program','EUR'),
('Eventide','EVE'),
('Exodus','EX'),
('Fallen Empires','FE'),
('Fate Reforged','FRF'),
('Fifth Dawn','FD'),
('Fifth Edition','5E'),
('Fourth Edition','4E'),
('Friday Night Magic','FNM'),
('From the Vault: Angels','V15'),
('From the Vault: Annihilation (2014)','V14'),
('From the Vault: Dragons','V08'),
('From the Vault: Exiled','V09'),
('From the Vault: Legends','V11'),
('From the Vault: Lore','V16'),
('From the Vault: Realms','V12'),
('From the Vault: Relics','V10'),
('From the Vault: Twenty','V13'),
('Future Sight','FUT'),
('Gatecrash','GTC'),
('Grand Prix','GPX'),
('Guildpact','GP'),
('Guru','GUR'),
('Happy Holidays','HHO'),
('Homelands','HL'),
('Hour of Devastation','HOU'),
('Ice Age','IA'),
('Innistrad','ISD'),
('Invasion','IN'),
('Ixalan','XLN'),
('Journey into Nyx','JOU'),
('Judge Gift Program','JCG'),
('Judgment','JU'),
('Kaladesh','KLD'),
('Khans of Tarkir','KTK'),
('Legend Membership','LGM'),
('Legends','LG'),
('Legions','LE'),
('Limited Edition Alpha','A'),
('Limited Edition Beta','B'),
('Lorwyn','LRW'),
('Magic 2010','M10'),
('Magic 2011','M11'),
('Magic 2012','M12'),
('Magic 2013','M13'),
('Magic 2014 Core Set','M14'),
('Magic 2015 Core Set','M15'),
('Magic Game Day Cards','GDC'),
('Magic Origins','ORI'),
('Magic Player Rewards','REW'),
('Magic: The Gathering Launch Parties','GLP'),
('Magic: The Gathering-Commander','CMD'),
('Magic: The Gathering—Conspiracy','CNS'),
('Magic: The Gathering—Conspiracy "Conspiracies"','CNSC'),
('Masterpiece Series: Amonkhet Invocations','AKHM'),
('Masterpiece Series: Kaladesh Inventions','MPS'),
('Masters Edition','ME'),
('Masters Edition II','ME2'),
('Masters Edition III','ME3'),
('Masters Edition IV','ME4'),
('Media Inserts','MBP'),
('Mercadian Masques','MM'),
('Mirage','MI'),
('Mirrodin','MR'),
('Mirrodin Besieged','MBS'),
('Modern Event Deck 2014','MD1'),
('Modern Masters','MMA'),
('Modern Masters 2015 Edition','MM2'),
('Modern Masters 2017 Edition','MM3'),
('Morningtide','MOR'),
('Nemesis','NE'),
('New Phyrexia','NPH'),
('Ninth Edition','9E'),
('Ninth Edition Box Set','9EB'),
('Oath of the Gatewatch','OGW'),
('Odyssey','OD'),
('Onslaught','ON'),
('Planar Chaos','PLC'),
('Planechase','PCH'),
('Planechase "Planes"','PCP'),
('Planechase 2012 Edition','PC2'),
('Planechase 2012 Edition "Planes" and "Phenomena"','PP2'),
('Planechase Anthology','PCA'),
('Planechase Anthology "Planes" and "Phenomena"','PCAP'),
('Planeshift','PS'),
('Portal','PT'),
('Portal Second Age','P2'),
('Portal Three Kingdoms','P3'),
('Premium Deck Series: Fire and Lightning','FAL'),
('Premium Deck Series: Graveborn','GRV'),
('Premium Deck Series: Slivers','SLI'),
('Prerelease Events','PRE'),
('Pro Tour','PRO'),
('Prophecy','PY'),
('Ravnica: City of Guilds','RAV'),
('Release Events','RLS'),
('Return to Ravnica','RTR'),
('Revised Edition','R'),
('Rise of the Eldrazi','ROE'),
('Saviors of Kamigawa','SOK'),
('Scars of Mirrodin','SOM'),
('Scourge','SC'),
('Seventh Edition','7E'),
('Shadowmoor','SHM'),
('Shadows over Innistrad','SOI'),
('Shards of Alara','ALA'),
('Starter 1999','ST'),
('Starter 2000','S2'),
('Stronghold','SH'),
('Summer of Magic','SUM'),
('Super Series','SS'),
('Tempest','TE'),
('Tempest Remastered','TPR'),
('Tenth Edition','10E'),
('The Dark','DK'),
('Theros','THS'),
('Time Spiral','TSP'),
('Time Spiral "Timeshifted"','TSB'),
('Torment','TO'),
('Two-Headed Giant Tournament','2HG'),
('Ugin''s Fate promos','UFRF'),
('Unglued','UG'),
('Unhinged','UNH'),
('Unlimited Edition','U'),
('Urza''s Destiny','UD'),
('Urza''s Legacy','UL'),
('Urza''s Saga','US'),
('Vintage Masters','VMA'),
('Visions','VI'),
('Weatherlight','WL'),
('Welcome Deck 2016','W16'),
('Welcome Deck 2017','W17'),
('World Magic Cup Qualifiers','WCQ'),
('Worlds','WRL'),
('Worldwake','WWK'),
('WPN/Gateway','GTW'),
('Zendikar','ZEN'),
('Zendikar Expeditions','EXP');